### ISSUE TITLE
Cannot run hvcc with only patch name.

### ISSUE THREAD

**Issue by Borey345** [Wasted-Audio/hvcc#163]
I have installed the 0.10.0 release of hvcc, Python 3.9.18

Trying to run 'hvcc D:\work\PCG\pdPatches\nr\_main.pd'

It gives:
**Traceback (most recent call last):
  File "C:\Users\rWX1203416\Anaconda3\envs\heavy\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rWX1203416\Anaconda3\envs\heavy\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rWX1203416\Anaconda3\envs\heavy\Scripts\hvcc.exe\__main__.py", line 7, in <module>
  File "C:\Users\rWX1203416\Anaconda3\envs\heavy\lib\site-packages\hvcc\__init__.py", line 350, in main
    results = compile_dataflow(
  File "C:\Users\rWX1203416\Anaconda3\envs\heavy\lib\site-packages\hvcc\__init__.py", line 186, in compile_dataflow
    subst_name = re.sub(r'\W', '_', patch_name)
  File "C:\Users\rWX1203416\Anaconda3\envs\heavy\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

After looking at __init__.py, I discovered that patch_meta_file is None, thus patch_name is None. Then on line 186 it fails.

Am I doing something wrong? Is the '--meta' parameter mandatory?

**Comment by dromer** [comment]
Hmm, shouldn't be. You do have to give the patch name using the `-n` flag.

However I'm considering to just use the default name `heavy` or something when it is not supplied.
I've also ran into the issue of forgetting the name flag and sometimes I just really don't care to name the export I'm working on or testing.

Thank you for the report to remind me to find a permanent fix ;)

**Comment by dromer** [comment]
ok setting a default name now. will be available in pip on the next release. Until then you will have to give `-n <somename>` argument when compiling.

**Comment by Borey345** [comment]
Ok, great! It is just a bit discouraging, when you start using the tool and it gives you some python error with the simplest patch and command from the documentation :-)

**Comment by dromer** [comment]
Just use it with the `-n/--name` flag for now :)
